// Client2-React/src/App.tsx
import React, { useEffect } from 'react';

// PrimeReact Imports
import { Card } from 'primereact/card';
import { Button } from 'primereact/button';
import { Tag } from 'primereact/tag';
import { ProgressSpinner } from 'primereact/progressspinner';
import { Divider } from 'primereact/divider';
import { Toast } from 'primereact/toast';

// Context and Hooks
import { AppProvider, useAppContext, useAuth, getHealthyComponentsCount, getReactAppComponents } from './context/AppContext';
import { useApi } from './hooks/useApi';

// Components
import DeliveryComponent from './components/DeliveryComponent';
import SupplierComponent from './components/SupplierComponent';
import SalesComponent from './components/SalesComponent';
import LoginComponent from './components/LoginComponent';

// Styles
import './App.css';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

// Main App Content Component
const AppContent: React.FC = () => {
  const { state, dispatch } = useAppContext();
  const { user, isAuthenticated, logout } = useAuth();
  const { loadSystemHealth, testConnection } = useApi();

  useEffect(() => {
    loadSystemHealth();
  }, [loadSystemHealth]);

  const switchView = (view: 'dashboard' | 'sales' | 'deliveries' | 'suppliers') => {
    dispatch({ type: 'SET_CURRENT_VIEW', payload: view });
  };

  const hasAccess = (feature: string): boolean => {
    if (!user) return false;

    switch (feature) {
      case 'dashboard':
        return true; // All authenticated users can see dashboard
      case 'sales':
        return user.role === 'sales_rep' || user.role === 'admin';
      case 'deliveries':
        return user.role === 'delivery_manager' || user.role === 'sales_rep' || user.role === 'admin';
      case 'suppliers':
        return user.role === 'inventory_manager' || user.role === 'admin';
      default:
        return false;
    }
  };

  const getHealthStatusClass = (): string => {
    if (!state.systemHealth) return 'unknown';
    return state.systemHealth.isHealthy ? 'healthy' : 'degraded';
  };

  const handleLogout = async () => {
    await logout();
  };

  // Show login component if user is not authenticated
  if (!isAuthenticated) {
    return <LoginComponent />;
  }

  return (
    <div className="app-container">
      <Toast />

      {/* Header */}
      <header className="app-header">
        <div className="header-content">
          <div className="logo-section">
            <h1 className="app-title">🏪 PoliMarket React Client - CBSE Architecture</h1>
            <p className="app-subtitle">Component-Based Software Engineering Implementation</p>
          </div>

          {/* User Info Section */}
          <div className="user-info-section">
            <div className="user-details">
              <span className="user-name">
                <i className="pi pi-user"></i>
                {user?.nombre && user?.apellido
                  ? `${user.nombre} ${user.apellido}`
                  : user?.username}
              </span>
              <span className="user-role">
                {user?.role === 'sales_rep' ? 'Vendedor' :
                 user?.role === 'delivery_manager' ? 'Gestor de Entregas' :
                 user?.role === 'admin' ? 'Administrador' : user?.role}
              </span>
            </div>
            <Button
              icon="pi pi-sign-out"
              className="p-button-text p-button-plain"
              onClick={handleLogout}
              tooltip="Cerrar Sesión"
              tooltipOptions={{ position: 'bottom' }}
            />
          </div>

          {/* System Health Indicator */}
          <div className={`health-indicator ${getHealthStatusClass()}`}>
            <div className="health-icon">
              {state.isLoadingHealth ? (
                <ProgressSpinner style={{ width: '2rem', height: '2rem' }} strokeWidth="4" />
              ) : (
                <span>
                  {state.systemHealth?.isHealthy ? '✅' :
                   state.systemHealth ? '⚠️' : '❌'}
                </span>
              )}
            </div>
            <div className="health-info">
              <div className="health-status">
                {state.isLoadingHealth ? 'Checking...' : (state.systemHealth?.overallStatus || 'Unknown')}
              </div>
              {state.systemHealth && (
                <div className="health-details">
                  {getHealthyComponentsCount(state.systemHealth).healthy}/
                  {getHealthyComponentsCount(state.systemHealth).total} Components Healthy
                </div>
              )}
            </div>
            <Button
              icon="pi pi-refresh"
              onClick={loadSystemHealth}
              disabled={state.isLoadingHealth}
              loading={state.isLoadingHealth}
              className="p-button-rounded p-button-text p-button-sm"
              tooltip="Refresh System Health"
            />
          </div>
        </div>
      </header>

      {/* Navigation */}
      <nav className="app-navigation">
        <div className="nav-content">
          {hasAccess('dashboard') && (
            <Button
              label="Dashboard"
              icon="pi pi-chart-bar"
              className={`nav-btn ${state.currentView === 'dashboard' ? 'active' : ''}`}
              onClick={() => switchView('dashboard')}
            />
          )}
          {hasAccess('sales') && (
            <Button
              label="RF2: Sales"
              icon="pi pi-shopping-cart"
              className={`nav-btn ${state.currentView === 'sales' ? 'active' : ''}`}
              onClick={() => switchView('sales')}
            />
          )}
          {hasAccess('deliveries') && (
            <Button
              label="RF4: Deliveries"
              icon="pi pi-truck"
              className={`nav-btn ${state.currentView === 'deliveries' ? 'active' : ''}`}
              onClick={() => switchView('deliveries')}
            />
          )}
          {hasAccess('suppliers') && (
            <Button
              label="RF5: Suppliers"
              icon="pi pi-building"
              className={`nav-btn ${state.currentView === 'suppliers' ? 'active' : ''}`}
              onClick={() => switchView('suppliers')}
            />
          )}
        </div>
      </nav>

      {/* Main Content */}
      <main className="app-main">
        {state.currentView === 'dashboard' && (
          <div className="dashboard-view">
            <div className="dashboard-header">
              <h2>🏠 System Dashboard</h2>
              <p>Overview of PoliMarket CBSE System Components</p>
            </div>

            {/* System Overview Cards */}
            <div className="overview-grid">
              {/* System Health Card */}
              <Card className={`health-card fade-in ${getHealthStatusClass()}`}>
                <div className="card-header-content">
                  <h3><i className="pi pi-heart"></i> System Health</h3>
                  <Tag
                    value={state.systemHealth?.overallStatus || 'Unknown'}
                    severity={state.systemHealth?.isHealthy ? 'success' : 'danger'}
                  />
                </div>

                {state.systemHealth && (
                  <>
                    <div className="health-metrics">
                      <div className="metric-grid">
                        <div className="metric">
                          <span className="metric-label">Components</span>
                          <span className="metric-value">{getHealthyComponentsCount(state.systemHealth).total}</span>
                        </div>
                        <div className="metric">
                          <span className="metric-label">Healthy</span>
                          <span className="metric-value healthy">{getHealthyComponentsCount(state.systemHealth).healthy}</span>
                        </div>
                        <div className="metric">
                          <span className="metric-label">Issues</span>
                          <span className="metric-value issues">
                            {getHealthyComponentsCount(state.systemHealth).total - getHealthyComponentsCount(state.systemHealth).healthy}
                          </span>
                        </div>
                      </div>
                    </div>

                    <Divider />

                    <div className="components-list">
                      {state.systemHealth && Object.entries(getReactAppComponents(state.systemHealth)).map(([key, component]) => (
                        <div key={key} className="component-status">
                          <span className="component-name">{component.componentName}</span>
                          <Tag
                            value={component.isHealthy ? 'Healthy' : 'Error'}
                            severity={component.isHealthy ? 'success' : 'danger'}
                          />
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </Card>

              {/* RF4 Deliveries Card */}
              <Card className="rf-card rf4-card fade-in">
                <div className="card-header-content">
                  <h3><i className="pi pi-truck"></i> RF4: Deliveries</h3>
                  <Tag value="Active" severity="success" />
                </div>

                <p>Delivery management and logistics tracking system</p>
                <ul className="feature-list">
                  <li><i className="pi pi-check text-green-500"></i> Delivery Scheduling</li>
                  <li><i className="pi pi-check text-green-500"></i> Status Tracking</li>
                  <li><i className="pi pi-check text-green-500"></i> Route Optimization</li>
                  <li><i className="pi pi-check text-green-500"></i> Confirmation System</li>
                </ul>

                <Button
                  label="Open Deliveries"
                  icon="pi pi-arrow-right"
                  onClick={() => switchView('deliveries')}
                  className="w-full mt-3"
                />
              </Card>

              {/* RF5 Suppliers Card */}
              <Card className="rf-card rf5-card fade-in">
                <div className="card-header-content">
                  <h3><i className="pi pi-building"></i> RF5: Suppliers</h3>
                  <Tag value="Active" severity="success" />
                </div>

                <p>Supplier management and performance tracking system</p>
                <ul className="feature-list">
                  <li><i className="pi pi-check text-green-500"></i> Supplier Registration</li>
                  <li><i className="pi pi-check text-green-500"></i> Performance Metrics</li>
                  <li><i className="pi pi-check text-green-500"></i> Category Management</li>
                  <li><i className="pi pi-check text-green-500"></i> Evaluation System</li>
                </ul>

                <Button
                  label="Open Suppliers"
                  icon="pi pi-arrow-right"
                  onClick={() => switchView('suppliers')}
                  className="w-full mt-3"
                />
              </Card>

              {/* Architecture Info Card */}
              {/* <Card className="architecture-card fade-in">
                <div className="card-header-content">
                  <h3><i className="pi pi-cog"></i> CBSE Architecture</h3>
                  <Tag value="Implemented" severity="success" />
                </div>

                <p>Component-Based Software Engineering principles applied</p>
                <ul className="feature-list">
                  <li><i className="pi pi-check text-green-500"></i> Separation of Concerns</li>
                  <li><i className="pi pi-check text-green-500"></i> Interface-Based Design</li>
                  <li><i className="pi pi-check text-green-500"></i> Loose Coupling</li>
                  <li><i className="pi pi-check text-green-500"></i> High Reusability</li>
                </ul>

                <Divider />

                <div className="architecture-stats">
                  <div className="stat-grid">
                    <div className="stat">
                      <span className="stat-value">6</span>
                      <span className="stat-label">Components</span>
                    </div>
                    <div className="stat">
                      <span className="stat-value">32</span>
                      <span className="stat-label">Endpoints</span>
                    </div>
                  </div>
                </div>
              </Card> */}
            </div>

            {/* API Information */}
            <Card className="api-info-section fade-in">
              <div className="card-header-content">
                <h3><i className="pi pi-link"></i> API Connection Information</h3>
                <Button
                  label="Test Connection"
                  icon="pi pi-wifi"
                  onClick={testConnection}
                  className="p-button-outlined p-button-sm"
                />
              </div>

              <div className="api-details">
                <div className="api-item">
                  <span className="api-label"><i className="pi pi-server"></i> Base URL:</span>
                  <span className="api-value">http://localhost:5001/api</span>
                </div>
                <div className="api-item">
                  <span className="api-label"><i className="pi pi-book"></i> Swagger UI:</span>
                  <span className="api-value">
                    <a href="http://localhost:5001" target="_blank" rel="noopener noreferrer" className="api-link">
                      http://localhost:5001 <i className="pi pi-external-link"></i>
                    </a>
                  </span>
                </div>
                <div className="api-item">
                  <span className="api-label"><i className="pi pi-heart"></i> Health Check:</span>
                  <span className="api-value">
                    <a href="http://localhost:5001/api/Integracion/health" target="_blank" rel="noopener noreferrer" className="api-link">
                      /api/Integracion/health <i className="pi pi-external-link"></i>
                    </a>
                  </span>
                </div>
              </div>
            </Card>
          </div>
        )}

        {state.currentView === 'sales' && hasAccess('sales') && <SalesComponent />}
        {state.currentView === 'deliveries' && hasAccess('deliveries') && <DeliveryComponent />}
        {state.currentView === 'suppliers' && hasAccess('suppliers') && <SupplierComponent />}
      </main>

      {/* Footer */}
      <footer className="app-footer">
        <div className="footer-content">
          <p>&copy; 2024 PoliMarket CBSE - Component-Based Software Engineering Implementation</p>
          <p>React Client consuming RF4 (Deliveries) and RF5 (Suppliers) components</p>
        </div>
      </footer>
    </div>
  );
};

// Main App Component with Provider
const App: React.FC = () => {
  return (
    <AppProvider>
      <AppContent />
    </AppProvider>
  );
};

export default App;

// Client1-Angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService } from 'primeng/api';
import { ApiService, SystemHealthResponse, ComponentHealth } from './services/api.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'PoliMarket Angular Client - CBSE Architecture';

  currentView: 'dashboard' | 'authorization' | 'inventory-dashboard' | 'suppliers' = 'dashboard';
  systemHealth: SystemHealthResponse | null = null;
  isLoadingHealth = false;

  // HR Authentication
  currentHRUser: any = null;
  hrLoginCode: string = '';
  isLoggingIn = false;

  // Angular App Component Filter - Only show components used in Angular app
  private readonly ANGULAR_APP_COMPONENTS = [
    { key: 'autorizacion', names: ['Autorizacion', 'Authorization', 'RF1'] },
    { key: 'hr', names: ['HR', 'Recursos Humanos', 'Human Resources', 'RH', 'Empleados'] },
    { key: 'inventario', names: ['Inventario', 'nventario', 'Inventory', 'RF3'] }
  ];

  constructor(
    private apiService: ApiService,
    private messageService: MessageService
  ) {}

  ngOnInit() {
    this.loadSystemHealth();
    this.loadHREmployees();
  }

  switchView(view: 'dashboard' | 'authorization' | 'inventory-dashboard' | 'suppliers') {
    // Only allow navigation if HR user is logged in
    if (!this.currentHRUser) {
      this.messageService.add({
        severity: 'warn',
        summary: 'Acceso Restringido',
        detail: 'Debe iniciar sesión como empleado de RH para acceder a esta aplicación'
      });
      return;
    }
    this.currentView = view;
  }

  // HR Authentication Methods
  hrEmployees: any[] = [];

  loadHREmployees() {
    this.apiService.getHREmployees().subscribe({
      next: (employees) => {
        this.hrEmployees = employees;
      },
      error: (error) => {
        console.error('Error loading HR employees:', error);
      }
    });
  }

  loginHR() {
    if (!this.hrLoginCode.trim()) {
      this.messageService.add({
        severity: 'warn',
        summary: 'Código Requerido',
        detail: 'Por favor ingrese su código de empleado RH'
      });
      return;
    }

    this.isLoggingIn = true;

    // Find HR employee by code
    const hrEmployee = this.hrEmployees.find(emp => emp.id === this.hrLoginCode.trim());

    setTimeout(() => {
      if (hrEmployee) {
        this.currentHRUser = hrEmployee;
        this.messageService.add({
          severity: 'success',
          summary: 'Acceso Autorizado',
          detail: `Bienvenido ${hrEmployee.nombre}`
        });
      } else {
        this.messageService.add({
          severity: 'error',
          summary: 'Acceso Denegado',
          detail: 'Código de empleado RH no válido. Solo personal de RH puede acceder a esta aplicación.'
        });
      }
      this.isLoggingIn = false;
    }, 1000);
  }

  logoutHR() {
    this.currentHRUser = null;
    this.hrLoginCode = '';
    this.currentView = 'dashboard';
    this.messageService.add({
      severity: 'info',
      summary: 'Sesión Cerrada',
      detail: 'Ha cerrado sesión exitosamente'
    });
  }

  loadSystemHealth() {
    this.isLoadingHealth = true;
    this.apiService.getSystemHealth().subscribe({
      next: (health) => {
        this.systemHealth = health;
        this.isLoadingHealth = false;
      },
      error: (error) => {
        console.error('Error loading system health:', error);
        this.isLoadingHealth = false;
      }
    });
  }

  getHealthStatusClass(): string {
    if (!this.systemHealth) return 'unknown';
    return this.systemHealth.isHealthy ? 'healthy' : 'degraded';
  }

  getComponentHealthCount(): { healthy: number; total: number } {
    if (!this.systemHealth?.componentsHealth) {
      return { healthy: 0, total: 0 };
    }

    // Filter to only show Angular app components
    const angularComponents = Object.values(this.systemHealth.componentsHealth).filter(component =>
      this.ANGULAR_APP_COMPONENTS.some(angularComp =>
        angularComp.names.some(name =>
          component.componentName.toLowerCase().includes(name.toLowerCase()) ||
          name.toLowerCase().includes(component.componentName.toLowerCase())
        )
      )
    );

    return {
      healthy: angularComponents.filter(c => c.isHealthy).length,
      total: angularComponents.length
    };
  }

  // Get filtered components for Angular app
  getAngularAppComponents(): { [key: string]: ComponentHealth } {
    if (!this.systemHealth?.componentsHealth) {
      return {};
    }

    const filteredComponents: { [key: string]: ComponentHealth } = {};

    Object.entries(this.systemHealth.componentsHealth).forEach(([key, component]) => {
      if (this.ANGULAR_APP_COMPONENTS.some(angularComp =>
        angularComp.names.some(name =>
          component.componentName.toLowerCase().includes(name.toLowerCase()) ||
          name.toLowerCase().includes(component.componentName.toLowerCase())
        )
      )) {
        filteredComponents[key] = component;
      }
    });

    return filteredComponents;
  }
}
<!-- Toast Messages -->
<p-toast></p-toast>

<!-- Main Application Container -->
<div class="app-container">
  <!-- Header (only shown when HR user is logged in) -->
  <header class="app-header" *ngIf="currentHRUser">
    <div class="header-content">
      <div class="logo-section">
        <h1 class="app-title">🏪 {{ title }}</h1>
        <p class="app-subtitle">Component-Based Software Engineering Implementation</p>
      </div>

      <!-- System Health Indicator -->
      <div class="health-indicator" [ngClass]="getHealthStatusClass()">
        <div class="health-icon">
          <p-progressSpinner
            *ngIf="isLoadingHealth"
            styleClass="w-2rem h-2rem"
            strokeWidth="4"
          ></p-progressSpinner>
          <span *ngIf="!isLoadingHealth && systemHealth?.isHealthy">✅</span>
          <span *ngIf="!isLoadingHealth && !systemHealth?.isHealthy">⚠️</span>
          <span *ngIf="!isLoadingHealth && !systemHealth">❌</span>
        </div>
        <div class="health-info">
          <div class="health-status">
            {{ isLoadingHealth ? 'Checking...' : (systemHealth?.overallStatus || 'Unknown') }}
          </div>
          <div class="health-details" *ngIf="systemHealth">
            {{ getComponentHealthCount().healthy }}/{{ getComponentHealthCount().total }} Components Healthy
          </div>
        </div>
        <p-button
          icon="pi pi-refresh"
          (onClick)="loadSystemHealth()"
          [disabled]="isLoadingHealth"
          [loading]="isLoadingHealth"
          styleClass="p-button-rounded p-button-text p-button-sm"
          pTooltip="Refresh System Health"
        ></p-button>
      </div>
    </div>
  </header>

  <!-- HR Login Section (shown when not logged in) -->
  <div class="hr-login-section" *ngIf="!currentHRUser">
    <div class="login-container">
      <div class="login-card">
        <div class="login-header">
          <i class="pi pi-lock"></i>
          <h2>Acceso Restringido</h2>
          <p>Solo Personal RH</p>
        </div>

        <div class="login-form">
          <p>Esta aplicación está destinada exclusivamente para el personal de Recursos Humanos.</p>

          <div class="input-group">
            <label for="hrCode">Código de Empleado RH</label>
            <input
              pInputText
              id="hrCode"
              [(ngModel)]="hrLoginCode"
              placeholder="Ej: HR001, HR002, HR003"
              (keyup.enter)="loginHR()"
              class="w-full"
            />
          </div>

          <p-button
            label="Iniciar Sesión"
            icon="pi pi-sign-in"
            [loading]="isLoggingIn"
            (onClick)="loginHR()"
            styleClass="w-full login-button"
          ></p-button>
        </div>
      </div>
    </div>
  </div>

  <!-- Navigation (only shown after HR login) -->
  <nav class="app-navigation" *ngIf="currentHRUser">
    <div class="nav-header">
      <div class="user-info">
        <i class="pi pi-user"></i>
        <span>{{currentHRUser.nombre}} ({{currentHRUser.id}})</span>
        <p-button
          label="Cerrar Sesión"
          icon="pi pi-sign-out"
          (onClick)="logoutHR()"
          styleClass="p-button-outlined p-button-sm"
        ></p-button>
      </div>
    </div>

    <div class="nav-content">
      <p-button
        label="Dashboard"
        icon="pi pi-chart-bar"
        [styleClass]="'nav-btn ' + (currentView === 'dashboard' ? 'active' : '')"
        (onClick)="switchView('dashboard')"
      ></p-button>
      <p-button
        label="RF1: Gestión de Autorización (RH)"
        icon="pi pi-users"
        [styleClass]="'nav-btn ' + (currentView === 'authorization' ? 'active' : '')"
        (onClick)="switchView('authorization')"
      ></p-button>

      <p-button
        label="RF3: Inventory"
        icon="pi pi-box"
        [styleClass]="'nav-btn ' + (currentView === 'inventory-dashboard' ? 'active' : '')"
        (onClick)="switchView('inventory-dashboard')"
      ></p-button>
      <p-button
        label="RF5: Suppliers"
        icon="pi pi-building"
        [styleClass]="'nav-btn ' + (currentView === 'suppliers' ? 'active' : '')"
        (onClick)="switchView('suppliers')"
      ></p-button>


    </div>
  </nav>

  <!-- Main Content Area (only shown when HR user is logged in) -->
  <main class="app-main" *ngIf="currentHRUser">
    <!-- Dashboard View -->
    <div *ngIf="currentView === 'dashboard'" class="dashboard-view">
      <div class="dashboard-header">
        <h2>🏠 System Dashboard</h2>
        <p>Overview of PoliMarket CBSE System Components</p>
      </div>

      <!-- System Overview Cards -->
      <div class="overview-grid">
        <!-- System Health Card -->
        <p-card styleClass="health-card fade-in" [ngClass]="getHealthStatusClass()">
          <ng-template pTemplate="header">
            <div class="card-header-content">
              <h3><i class="pi pi-heart"></i> System Health</h3>
              <p-tag
                [value]="systemHealth?.overallStatus || 'Unknown'"
                [severity]="systemHealth?.isHealthy ? 'success' : 'danger'"
              ></p-tag>
            </div>
          </ng-template>

          <div class="health-metrics" *ngIf="systemHealth">
            <div class="p-grid">
              <div class="p-col-4">
                <div class="metric text-center">
                  <span class="metric-label">Components</span>
                  <span class="metric-value">{{ getComponentHealthCount().total }}</span>
                </div>
              </div>
              <div class="p-col-4">
                <div class="metric text-center">
                  <span class="metric-label">Healthy</span>
                  <span class="metric-value healthy">{{ getComponentHealthCount().healthy }}</span>
                </div>
              </div>
              <div class="p-col-4">
                <div class="metric text-center">
                  <span class="metric-label">Issues</span>
                  <span class="metric-value issues">{{ getComponentHealthCount().total - getComponentHealthCount().healthy }}</span>
                </div>
              </div>
            </div>
          </div>

          <p-divider *ngIf="systemHealth?.componentsHealth"></p-divider>

          <div class="components-list" *ngIf="systemHealth?.componentsHealth">
            <div
              *ngFor="let component of (getAngularAppComponents() | keyvalue)"
              class="component-status flex justify-content-between align-items-center mb-2"
            >
              <span class="component-name">{{ component.value.componentName }}</span>
              <p-tag
                [value]="component.value.isHealthy ? 'Healthy' : 'Error'"
                [severity]="component.value.isHealthy ? 'success' : 'danger'"
              ></p-tag>
            </div>
          </div>
        </p-card>

        <!-- RF1 Authorization Card -->
        <p-card styleClass="rf-card rf1-card fade-in">
          <ng-template pTemplate="header">
            <div class="card-header-content">
              <h3><i class="pi pi-shield"></i> RF1: Authorization</h3>
              <p-tag value="Active" severity="success"></p-tag>
            </div>
          </ng-template>

          <p>Seller authorization and HR management system</p>
          <ul class="feature-list">
            <li><i class="pi pi-check text-green-500"></i> Seller Authorization</li>
            <li><i class="pi pi-check text-green-500"></i> Authorization Validation</li>
            <li><i class="pi pi-check text-green-500"></i> HR Employee Management</li>
            <li><i class="pi pi-check text-green-500"></i> Permission Control</li>
          </ul>

          <ng-template pTemplate="footer">
            <p-button
              label="Open HR Management"
              icon="pi pi-arrow-right"
              (onClick)="switchView('authorization')"
              styleClass="w-full"
            ></p-button>
          </ng-template>
        </p-card>

        <!-- RF3 Inventory Card -->
        <p-card styleClass="rf-card rf3-card fade-in">
          <ng-template pTemplate="header">
            <div class="card-header-content">
              <h3><i class="pi pi-box"></i> RF3: Inventory</h3>
              <p-tag value="Active" severity="success"></p-tag>
            </div>
          </ng-template>

          <p>Inventory management and stock control system</p>
          <ul class="feature-list">
            <li><i class="pi pi-check text-green-500"></i> Stock Availability Check</li>
            <li><i class="pi pi-check text-green-500"></i> Inventory Updates</li>
            <li><i class="pi pi-check text-green-500"></i> Stock Alerts</li>
            <li><i class="pi pi-check text-green-500"></i> Movement Tracking</li>
          </ul>

          <ng-template pTemplate="footer">
            <p-button
              label="Open Inventory"
              icon="pi pi-arrow-right"
              (onClick)="switchView('inventory-dashboard')"
              styleClass="w-full"
            ></p-button>
          </ng-template>
        </p-card>

        <!-- Architecture Info Card -->
        <!-- <p-card styleClass="architecture-card fade-in">
          <ng-template pTemplate="header">
            <div class="card-header-content">
              <h3><i class="pi pi-cog"></i> CBSE Architecture</h3>
              <p-tag value="Implemented" severity="success"></p-tag>
            </div>
          </ng-template>

          <p>Component-Based Software Engineering principles applied</p>
          <ul class="feature-list">
            <li><i class="pi pi-check text-green-500"></i> Separation of Concerns</li>
            <li><i class="pi pi-check text-green-500"></i> Interface-Based Design</li>
            <li><i class="pi pi-check text-green-500"></i> Loose Coupling</li>
            <li><i class="pi pi-check text-green-500"></i> High Reusability</li>
          </ul>

          <p-divider></p-divider>

          <div class="architecture-stats">
            <div class="p-grid">
              <div class="p-col-6">
                <div class="stat text-center">
                  <span class="stat-value">4</span>
                  <span class="stat-label">Components</span>
                </div>
              </div>
              <div class="p-col-6">
                <div class="stat text-center">
                  <span class="stat-value">27</span>
                  <span class="stat-label">Endpoints</span>
                </div>
              </div>
            </div>
          </div>
        </p-card> -->
      </div>

      <!-- API Information -->
      <p-card styleClass="api-info-section fade-in">
        <ng-template pTemplate="header">
          <div class="card-header-content">
            <h3><i class="pi pi-link"></i> API Connection Information</h3>
          </div>
        </ng-template>

        <div class="api-details">
          <div class="api-item">
            <span class="api-label"><i class="pi pi-server"></i> Base URL:</span>
            <span class="api-value">http://localhost:5001/api</span>
          </div>
          <div class="api-item">
            <span class="api-label"><i class="pi pi-book"></i> Swagger UI:</span>
            <span class="api-value">
              <a href="http://localhost:5001" target="_blank" class="api-link">
                http://localhost:5001 <i class="pi pi-external-link"></i>
              </a>
            </span>
          </div>
          <div class="api-item">
            <span class="api-label"><i class="pi pi-heart"></i> Health Check:</span>
            <span class="api-value">
              <a href="http://localhost:5001/api/Integracion/health" target="_blank" class="api-link">
                /api/Integracion/health <i class="pi pi-external-link"></i>
              </a>
            </span>
          </div>
        </div>
      </p-card>
    </div>



    <!-- Inventory Dashboard View -->
    <div *ngIf="currentView === 'inventory-dashboard'" class="component-view">
      <app-inventory-dashboard></app-inventory-dashboard>
    </div>

    <!-- Authorization View -->
    <div *ngIf="currentView === 'authorization'" class="component-view">
      <app-authorization></app-authorization>
    </div>

    <!-- Supplier Management View -->
    <div *ngIf="currentView === 'suppliers'" class="component-view">
      <app-supplier-management></app-supplier-management>
    </div>
  </main>

  <!-- Footer -->
  <footer class="app-footer">
    <div class="footer-content">
      <p>&copy; 2024 PoliMarket CBSE - Component-Based Software Engineering Implementation</p>
      <p>Angular Client consuming RF1 (Authorization) and RF3 (Inventory) components</p>
    </div>
  </footer>
</div>
